DROP TABLE IF EXISTS EVENT;  
CREATE TABLE EVENT (  
Event_Code INT AUTO_INCREMENT PRIMARY KEY,  
Event_Name VARCHAR(50) NOT NULL,  
Event_Desc VARCHAR(50) NOT NULL,  
Event_Place VARCHAR(50) NOT NULL,  
Event_Date VARCHAR(50) NOT NULL,  
Event_Capacity INT NOT NULL  
);  
